#!{{ pkgPathFor "core/bash" }}/bin/bash

# This doesn't actually exist yet, waiting on
# https://github.com/habitat-sh/habitat/issues/4923

# However, it doesn't mean we can't do it by tailing the log! (see ret-alb-remove.service in packer)

{{#if cfg.aws.alb_target_group_arn ~}}
  INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
  REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/[a-z]$//')

  # Remove from all ALBs, do not care about smoke since it takes time to determine if this is a smoke box.
  echo "Removing from alb group $ALB_GROUP"
  aws elbv2 deregister-targets --target-group-arn="{{ ../cfg.aws.alb_target_group_arn }}" --targets="Id=$INSTANCE_ID" --region "$REGION"
  aws elbv2 deregister-targets --target-group-arn="{{ ../cfg.aws.smoke_alb_target_group_arn }}" --targets="Id=$INSTANCE_ID" --region "$REGION"
{{/if}}
