#!{{ pkgPathFor "core/bash" }}/bin/bash

# This doesn't actually exist yet, waiting on
# https://github.com/habitat-sh/habitat/issues/4923

# However, it doesn't mean we can't do it by tailing the log!

{{#if cfg.aws.alb_target_group_arn ~}}
  INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
  REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/[a-z]$//')
  SMOKE=$(aws ec2 --region $REGION describe-instances |  jq -r ".Reservations | map(.Instances) | flatten | .[] | select(.InstanceId == \"$INSTANCE_ID\") | .Tags | .[] | select(.Key == \"smoke\") | .Value ")

  if [ "$SMOKE" == "true" ]; then
    ALB_GROUP="{{ ../cfg.aws.smoke_alb_target_group_arn }}"
  else
    ALB_GROUP="{{ ../cfg.aws.alb_target_group_arn }}"
  fi

  echo "Removing from alb group $ALB_GROUP"
  aws elbv2 deregister-targets --target-group-arn="$ALB_GROUP" --targets="Id=$INSTANCE_ID" --region "$REGION"
{{/if}}
