name: lint-and-test

on: [push, workflow_dispatch]

permissions: {}

jobs:
  test-current:
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-22.04'
          - 'ubuntu-24.04'

    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          elixir-version: '1.16.3-otp-25'
          otp-version: '25.3.2.20'
#       When changing versions, change it everywhere (check the README).

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            deps
            _build
          key: mix-${{ hashFiles('mix.lock') }}

      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix test


  test-matrix:
    # if a matrix-job with newer versions passes, advance the current versions!
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        versions:
          - elixir: '1.16.3-otp-25'
            otp: '25.3.2.20'
          - elixir: '1.16.3-otp-26'
            otp: '26.2.5.16'

          - elixir: '1.17.3-otp-25'
            otp: '25.3.2.20'
          - elixir: '1.17.3-otp-26'
            otp: '26.2.5.16'
          - elixir: '1.17.3-otp-27'
            otp: '27.3.4.6'

          - elixir: '1.18.4-otp-25'
            otp: '25.3.2.20'
          - elixir: '1.18.4-otp-26'
            otp: '26.2.5.16'
          - elixir: '1.18.4-otp-27'
            otp: '27.3.4.6'
          - elixir: '1.18.4-otp-28'
            otp: '28.3.1'

        os:
          - 'ubuntu-22.04'
          - 'ubuntu-24.04'

        exclude:
          - versions:   # current versions; already tested above
              elixir: '1.16.3-otp-25'
              otp: '25.3.2.20'

            os: 'ubuntu-22.04'

    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          elixir-version: ${{ matrix.versions.elixir }}
          otp-version: ${{ matrix.versions.otp }}

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            deps
            _build
          key: mix-${{ hashFiles('mix.lock') }}

      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix test


  pseudo-lint:
    continue-on-error: false   # `mix format` MUST be run before committing
    strategy:
      fail-fast: false
      matrix:
        versions:
          - elixir: '1.16.3-otp-25'
            otp: '25.3.2.20'

          - elixir: '1.17.3-otp-25'
            otp: '26.2.5.16'

          - elixir: '1.18.4-otp-27'
            otp: '27.3.4.6'

          - elixir: '1.18.4-otp-28'
            otp: '28.3.1'

    runs-on: 'ubuntu-24.04'

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          elixir-version: ${{ matrix.versions.elixir }}
          otp-version: ${{ matrix.versions.otp }}

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            deps
            _build
          key: mix-${{ hashFiles('mix.lock') }}

      - run: mix deps.get
      - run: mix format --check-formatted '{lib,priv,test,config}/**/*.{ex,exs}'
